version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      monitoring_net:

  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PUBLISH_PORT}:9292/tcp
    networks:
      - front_net
      - monitoring_net
    command: ["--debug", "-w", "2"]

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    # volumes:
    #   - ./post-py:/app
    networks:
      - back_net
      - front_net
      - monitoring_net

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
      - monitoring_net
    command: ["--debug", "-w", "2"]

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitoring_net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring_net
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  monitoring_net:
    ipam:
      config:
        - subnet: 10.0.3.0/24
